type: object
required:
  - id
  - description
  - toggleOnList
  - defaultState
properties:
  id:
    type: string
  description:
    type: string
  toggleOnList:
    type: boolean
  defaultState:
    type: boolean
